addSbtPlugin("org.jetbrains.scala"       % "sbt-ide-settings"    % "1.1.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.11")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.34")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.1")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"          % "4.1.1")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"            % "2.3.3")